update prontuario_personalizado
set titulo = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(titulo, '├é┬║','Âª')
,'├âÔÇí','Ã‡')
,'├âãÆ','Ã£')
,'├â┬º','Ã§')
,'├â┬ú','Ã£')
,'├â┬í','Ã¡')
,'├â┬ú','Ã£')
,'├â┬®','Ã©')
,'├â┬¬','Ãª')
,'├â┬│','Ã³')
,'├â┬Á','Ãµ')
,'├âÔÇ£','Ã“')
,'├â┬║','Ãº')
,'├âãÆO','Ãƒ')
,'├âÔÇ░','Ã‰')
,'├â┬¡','Ã­')
,'├â┬ì','Ã')
,'├â┼í','Ãš')
,'├â┼á','ÃŠ')
,'├â┬ü','Ã')
,'├âÔÇØ','Ã´')
,'├â┬┤','Ã´')
,'├âÔÇó','Ã•')
,'├é┬¬','Âª')
,'├âÔÇÜ','Ã”')
,'├âÔé¼','Ã')
,'├â┬ç','Ã‡')
,'├â┬á','Ã¡')
,'├â┬ó','Ã¢')
,'├é┬▓','2')
,'c├î┬º','Ã§')
,'A├îãÆ','Ã')
,'o├î┬ü','Ã³')
,'a├î┬ü','Ã¡')
,'E├î┬ü','Ã‰')
,'I├î┬ü','Ã')
,'├â┬▓','Ãµ')
,'e├îÔÇÜ','Ãª')
,'├â╦å','Ã‰')
,'├â┬╣','Ãš')
,'├ï┼ô','Ãµ')
,'├â┬ñ','Ã')
,'├âÔäó','Ãš')
,'├»ãÆ┬á',' ')
,'├â┬¿','Ã¨')
,'├â┬╝','Ã¼')
,'├»┬┐┬¢','Ã£o')
,'├óÔé¼ÔÇ£',' ')
,'├óÔé¼ÔÇØ',' ')
,'├óÔé¼Ôäó',' ')
,'├óÔé¼┬ó',' ')
,'├óÔé¼┼ô',' ')
,'├óÔé¼┬Ø',' ')
,'├óÔé¼',' ')
,'├é┬┤','')
,'├é┬á','')
,'├é┬¢','')
,'├é┬«','')
,'┬Ø','')
,'┬¿','')
where 1;